### PR TITLE
adding rabbitmq tags

### PR DESCRIPTION
**Pull request by deimosfr**
Hi,

Adding tags helps on deploying a specific role. I added them.

Thanks

### CODE REVIEW

**Comment by lyrixx** [comment]
Why don't your tag this role when you import in your playbook ?

**Comment by Mayeu** [comment]
Hello,

First, thank you for your pull request.

As @lyrixx propose, I'm generally a proponent of adding the tag you need when you import the role. I think that the advantages of this approach are:
- you don't clutter the tag namespace
- the tag become explicit because it is at the playbook level, and not hidden inside a role, meaning better & easier discoverability
- you can apply any rule you prefer on the tag naming, instead of being forced by the role creator, which may not have the same naming rule than you

What advantage do you see in term of usability of the role to have the tag directly in the playbook?

**Comment by deimosfr** [comment]
I don't think adding a tag anytime you are using this role make sense. I have several calling playbooks calling it, I don't think this is the most common way to do it.

**Comment by Mayeu** [comment]
Thank you for your contribution.

Sadly, and has you may have guessed, I don't use this project anymore, nor do I have the time to continue to maintain it. I may at some point start to use it again, but that is not on my priority right now.

Feel free to fork and improve, I can even link potential fork in the README.

Wishing you the best, and a gajillion more contribution in your lifetime 🙏✨

**Pull request closed without merging**
