### PR TITLE
Removed `tasks/install` path to make `copy` work with Ansible 2.

### PR DESCRIPTION
**Pull request by nhooey**
The parameter in the copy directive: `src: ../../files/rabbitmq.list`
breaks with Ansible 2 because the script is in the `tasks/install`
subdirectory. It's best to not make extra subdirectories.

### CODE REVIEW

**Comment by palvarez89** [comment]
This change seems to work, and would fix https://github.com/Mayeu/ansible-playbook-rabbitmq/issues/57

**Comment by gregorskii** [comment]
+1

**Comment by si14** [comment]
This issue breaks my builds. Is it possible to merge the PR?

**Comment by Mayeu** [comment]
Thank you for your contribution.

Sadly, and has you may have guessed, I don't use this project anymore, nor do I have the time to continue to maintain it. I may at some point start to use it again, but that is not on my priority right now.

Feel free to fork and improve, I can even link potential fork in the README.

Wishing you the best, and a gajillion more contribution in your lifetime 🙏✨

**Pull request closed without merging**
