### PR TITLE
Adding binary install method

### PR DESCRIPTION
**Pull request by BarthV**
( I had to create a branch a recreate this PR. Sorry for noise )

Hi !

Currently the playbook is using debian official repository.
This is great but with repo install method, we're not able to select / retrieve or pin a single version since RMQ repo is only exposing the latest one.

This PR add a bunch of attributes to control a new 'binary' install method :

```
This method computes the desired deb/rpm from rmq website.
It DL+Install (debian) or just install from url (rh)
```

The rest is unchanged.

Default behaviour is still to install from "repo" as it was done before.

I'd tested it on some debian/ubuntu/centos vagrant boxes and it is ok for me. But you can proceed for more checks if needed.

Thanks

### CODE REVIEW

**Comment by BarthV** [comment]
:up:

**Comment by BarthV** [comment]
:up: :angel: 
@Mayeu , any news about this ?

**Comment by BarthV** [comment]
:up: again.

@Mayeu please ;)

**Comment by BarthV** [comment]
:up: 
@Mayeu are you still alive :ghost:

**Comment by BarthV** [comment]
super soft-bump @Mayeu

**Comment by BarthV** [comment]
Bump again !

**Comment by Mayeu** [comment]
Thank you for your contribution.

Sadly, and has you may have guessed, I don't use this project anymore, nor do I have the time to continue to maintain it. I may at some point start to use it again, but that is not on my priority right now.

Feel free to fork and improve, I can even link potential fork in the README.

Wishing you the best, and a gajillion more contribution in your lifetime 🙏✨

**Pull request closed without merging**
